### ISSUE TITLE
Question about the algorithm

### ISSUE THREAD

**Issue by Hugo-cell111** [cskyl/SAM_WSSS#5]
Hi! In your Algorithm 1, if pseudo_labelsi is EMPTY then continue. But if I have no post-processing, then I will get no pseudo labels. Then how does the algorithm go on? Or do you mean the CAM result can be also regarded as a kind of vanilla pseudo label? Thanks!

**Comment by cskyl** [comment]
> Hi! In your Algorithm 1, if pseudo_labelsi is EMPTY then continue. But if I have no post-processing, then I will get no pseudo labels. Then how does the algorithm go on? Or do you mean the CAM result can be also regarded as a kind of vanilla pseudo label? Thanks!

Hi, thank you for your insightful question. When there's no post-processing is applied after obtaining the CAM, we assume that there exists an appropriate threshold for converting CAM into pseudo labels. Indeed, many WSSS methods provide a hyperparameter suitable for thresholding the CAM. But your are correct that without any post-processing, we might not able to get the optimal pseudo label from CAM. We have considered revising our algorithm to initially take the CAM result as input. However, we chose not to implement this because our goal was to design an algorithm which could work with the most general pseudo labels, which are the same format like FSSS labels, so that our algorithm to be compatible with other methods that produce a pseudo label, even if they don't necessarily produce CAM.

**Comment by Hugo-cell111** [comment]
Thanks!
