### ISSUE TITLE
The information about the pseudo label generated by TransCAM

### ISSUE THREAD

**Issue by ChunmengLiu1** [cskyl/SAM_WSSS#9]
Hi! Thank you for your good job!

when computing the overlap between the binary mask generated by SAM and pseudo label, what kind of format of pseudo labels? Is it also converted to the binary mask?
 
Thank you!

**Comment by cskyl** [comment]
Hi, thank you for your comment!
Yes, we converted into binary masks to compute the overlap ratio during the merging sections.
We found that you can potentially use more complex format (for example, we can get more information from the class activation map format), however, since some of the pseudo labels only comes we class labels, we just converted every class's label into binary format.
Thank you for your question and please let me know if you have further question :)
